### ISSUE TITLE
这个封装的功能很不错, 大佬是否考虑一下~~换个 webview

### ISSUE THREAD

**Issue by HolmesZhao** [xiubojin/JXBWebKit#1]
[KSWebView](https://github.com/kinsunlu/KSWebView) 这个 `webview` 可以让 `js` 按照 `oc` 的方式来进行调用, 把这个集成到大佬的 webview 上我想会更让人喜欢的~

**Comment by GreatLiyi** [comment]
怎么调用原生的方法

**Comment by xiubojin** [comment]
有这个想法，目前还在调研阶段，后续会支持这种调用方式。

**Comment by HolmesZhao** [comment]
加油, 看好你~万一以后我用的上就直接依赖你的库了😂

**Comment by GreatLiyi** [comment]
> 加油, 看好你~万一以后我用的上就直接依赖你的库了😂

说的好像你用作者的库会让作者感到荣幸一样

**Comment by HolmesZhao** [comment]
> > 加油, 看好你~万一以后我用的上就直接依赖你的库了😂
> 
> 说的好像你用作者的库会让作者感到荣幸一样

没毛病老铁
