### ISSUE TITLE
请问和NSHTTPCookieStorage 的cookie同步问题如何解决？

### ISSUE THREAD

**Issue by chipengliu** [xiubojin/JXBWebKit#11]
请问和NSHTTPCookieStorage 的cookie同步问题如何解决，WKWebview cookie不是和NSHTTPCookieStorage实时同步的

**Comment by xiubojin** [comment]
iOS11以上直接往WKWebView的cookie存储域写，iOS11以下往NSHTTPCookieStorage里写。
