### ISSUE TITLE
关于H5页面中AJAX请求拦截问题

### ISSUE THREAD

**Issue by hatjs880328s** [xiubojin/JXBWebKit#13]
H5页面中的ajax请求，我们根本就拦截不到吧。使用urlprotocol的时候body已经是null了。
你文章中说将body当做header存起来，并且将http更改为post是在这里处理吗？
谢谢回答

**Comment by xiubojin** [comment]
文章说的body当做header存起来，这种解决方法只适用于首次是post请求的情况。
因为webkit在独立进程工作，使用urlprotocol拦截的时候涉及到跨进程通信，为了通信效率webkit把post请求的body数据丢弃了，所以现在获取不到。
