### ISSUE TITLE
关于模板渲染

### ISSUE THREAD

**Issue by zhang759740844** [xiubojin/JXBWebKit#16]
您好，我在您的 Demo 中没有看到关于 HTML 模板渲染的相关逻辑啊。

**Comment by xiubojin** [comment]
模板渲染的逻辑在后端，看.go文件

**Comment by zhang759740844** [comment]
但是我有点不明白的是。模板渲染的模板难道不应该是在本地吗？然后在从服务端请求好数据然后在本地替换。

如果说模板渲染的逻辑在后端，那么通过 nuxt.js 或者 next.js 这种服务端渲染框架不是直接就可以拿到渲染好数据的 html 么？这样说的话，那些新闻客户端的新闻界面其实没有做什么，只是打开一个 webview 么？
