### ISSUE TITLE
关于页面拦截JS-confirm函数白屏问题

### ISSUE THREAD

**Issue by hatjs880328s** [xiubojin/JXBWebKit#18]
runJavaScriptConfirmPanelWithMessage
这个函数弹出的alertvc,将app推到后台，再回到前台，页面会白屏，点击任何一个alert 按钮
之后恢复，请问是复用引起的问题吗？

**Comment by xiubojin** [comment]
这个不是复用导致的，提示框和输入框也会这样吗？

**Comment by hatjs880328s** [comment]
是的，都会出先这个问题。
如果completionHandler()立马执行则不会出现这个问题。

**Comment by xiubojin** [comment]
这个是WKWebView的问题，暂时没发现如何引起的。
