### ISSUE TITLE
JXBWebview  如何在不同的控制器 复用

### ISSUE THREAD

**Issue by Rcrosp** [xiubojin/JXBWebKit#21]

**Comment by xiubojin** [comment]
从复用池（ReusePool）里获取。

**Comment by Rcrosp** [comment]
[[JXBWKWebViewPool sharedInstance] getReusedWebViewForHolder:self] 使用这个方法一次都没有调用过复用webview

**Comment by Rcrosp** [comment]
if (_reusableWebViewSet.count > 0) {
        webView = (JXBWKWebView *)[_reusableWebViewSet anyObject];
        [_reusableWebViewSet removeObject:webView];
        [_visiableWebViewSet addObject:webView];
        
        [webView webViewWillReuse];
    } else {
        webView = [[JXBWKWebView alloc] initWithFrame:CGRectZero];
        [_visiableWebViewSet addObject:webView];
    }
因为_reusableWebViewSet 这个一直都是未被添加
