### ISSUE TITLE
registerSupportProtocolWithHTTP:(BOOL)supportHTTP 请教

### ISSUE THREAD

**Issue by dustturtle** [xiubojin/JXBWebKit#22]
这里的参数在实际场景下怎么使用？ 我看demo里面设置的是NO，但发起的都是http请求？ 意思是不拦截吗？

**Comment by dustturtle** [comment]
WKMessageHandlerProtocol 这个的使用场景又是什么？》 🙏

**Comment by dustturtle** [comment]
jxb_loadRequestURLString  这一系列方法什么使用调用啊？

**Comment by xiubojin** [comment]
1、拦截http(s)的请求一定要谨慎，这回导致post请求body数据丢失，建议你不要拦截。
2、WKMessageHandlerProtocol是H5和native的通信协议。
3、一系列方法就是初始化栈方法，丢一个你要请求的资源地址进来。

**Comment by dustturtle** [comment]
多谢作者的耐心回复了！>___<
