### ISSUE TITLE
 MEM LEAKS

### ISSUE THREAD

**Issue by hatjs880328s** [xiubojin/JXBWebKit#23]
__block id observer = [[NSNotificationCenter defaultCenter] addObserverForName:UIApplicationDidFinishLaunchingNotification object:nil queue:nil usingBlock:^(NSNotification * _Nonnull note)

你好。
使用内存泄漏跟踪工具，检测到这里有内存泄漏。 

期待你的回复。

**Comment by xiubojin** [comment]
放心用，这么写没问题。
