### ISSUE TITLE
_backNavLeftItem的backImage为什么不设置成UIImageRenderingModeAlwaysOriginal？

### ISSUE THREAD

**Issue by xiruoruo** [xiubojin/JXBWebKit#26]
如果不设置成UIImageRenderingModeAlwaysOriginal，又没有提供其他属性改变返回按钮颜色，那么backImagePath这个属性的意义何在呢？

**Comment by xiubojin** [comment]
版本更新的时候把backImage的rendringMode误删了，已经改回来了。
