### ISSUE TITLE
Could not signal service com.apple.WebKit.

### ISSUE THREAD

**Issue by xiruoruo** [xiubojin/JXBWebKit#28]
Could not signal service com.apple.WebKit. WebContent: 113: Could not find specified service。这是什么错误哦，有遇到过的吗

**Comment by xiruoruo** [comment]
在网页成功后一会儿出现的，好像也不是必现

**Comment by xiubojin** [comment]
这个问题建议你google一下，可能是你某些其他的设置导致的。
