### ISSUE TITLE
所有网络断开后，所有的JXBWebView 页面打开后依然是上一次有网络时打开的页面。

### ISSUE THREAD

**Issue by HZRZCW** [xiubojin/JXBWebKit#3]
所有网络断开后，所有的JXBWebView 页面打开后依然是上一次有网络时打开的页面，这种体验我觉得不好，明明没有网络了，打开一个新的webview页面还是有内容，而且是其他页面的内容。应该参考微信的做法。

**Comment by xiubojin** [comment]
我这里没有出现，我想了解一下你的使用场景和操作路径，可以留一个你的联系方式吗，wechat或qq？

**Comment by xiubojin** [comment]
你是通过pool使用的JXBWebView吗？如果是通过pool获取JXBWebView，在这个WebView使用完后是否用pool进行了回收？如果没有进行回收就会出现你所说的情况。

---

2018年10月19日又提交了一个小版本，你看看你的问题还存在吗。

**Comment by HZRZCW** [comment]
不好意思，现在才来看，我重新试下一下最新的代码，发现之前是由于我注释掉了 [self registerSupportProtocolWithHTTP:NO schemes:@[@"post", kWKWebViewReuseScheme] protocolClass:[JXBWKCustomProtocol class]];这句代码导致的，如果注释掉就会出现我说的这种情况，不注释的话，如果没有网络的话就不会再加载之前旧的内容，如下图所示。请问这句代码一定要吗？[self registerSupportProtocolWithHTTP:NO schemes:@[@"post", kWKWebViewReuseScheme] protocolClass:[JXBWKCustomProtocol class]];
![fb403e4236303b8c0b9746b76aa26b50](https://user-images.githubusercontent.com/12219811/47293331-6c68f600-d63c-11e8-9a2c-7a12b6ed2cb2.png)

**Comment by xiubojin** [comment]
这句代码是保证WKWebView复用的关键，对工程内其他业务没有侵入性，对你有什么影响吗？

**Comment by HZRZCW** [comment]
对现有功能暂时没影响，只是有点担心审核被拒。

**Comment by xiubojin** [comment]
> 对现有功能暂时没影响，只是有点担心审核被拒。

我这边没什么影响。你要是担心被拒的话可以修改NSURLProtocol+WebKitSupport这个分类文件，把里面用到的私有api进行一下混淆。
我一会再更新一下吧，1.0.6。

**Comment by xiubojin** [comment]
> 对现有功能暂时没影响，只是有点担心审核被拒。

ok了，代码更新到1.0.6了。
