### ISSUE TITLE
FBRetainCycleDetector 检测到内存泄漏

### ISSUE THREAD

**Issue by LChao05** [xiubojin/JXBWebKit#34]
Possibly Memory Leak.
In case that JXBWKWebView should not be dealloced, override -willDealloc in JXBWKWebView by returning NO.
View-ViewController stack: [
	"TaskWallVC",
	"UIView",
	"JXBWKWebView",
	]

**Comment by xiubojin** [comment]
具体是哪？

**Comment by LChao05** [comment]
没看出来，你pod 'MLeaksFinder'到你的demo工程试一下，也会报内存泄漏

**Comment by xiubojin** [comment]
不用管，项目是没问题的。
