### ISSUE TITLE
关于Android端怎么用该协议

### ISSUE THREAD

**Issue by xiaolvyang** [xiubojin/JXBWebKit#36]
iOS封装的很好了，安卓端具体怎么样该协议呢，麻烦具体指点一下

**Comment by xiubojin** [comment]
修改bridge.js文件就可以了，让他们对自己的平台做一下适配。

**Comment by xiaolvyang** [comment]
bridge.js文件需要修改吗，可否指点一下

**Comment by xiubojin** [comment]
这个得看android那边具体怎么设计，比如他们可以把js调用的target、action、callback拼接到url后面，然后在native通过拦截url获取到target、action、callback，拿到这些参数后在native进行调用相应的功能。

**Comment by xiaolvyang** [comment]
多谢
