### ISSUE TITLE
关于webview返回

### ISSUE THREAD

**Issue by xiaolvyang** [xiubojin/JXBWebKit#37]
接入我的工程后，打开百度链接，进入二级详情页，会出现偶尔无法正常返回，点返回按钮直接从webview返回到原生页面，这种情况什么问题造成的呢

**Comment by xiubojin** [comment]
自己查一下不好吗

**Comment by xiaolvyang** [comment]
返回时打印webview.backForwardList.backlist.count,偶尔不能正常返回时，数值是0，应该是加载下一级也面时，上一级页面被干掉了，但是不知道问题出在哪里，可否指点一下

**Comment by xiubojin** [comment]
我试一下

**Comment by xiaolvyang** [comment]
好的，麻烦看看，进入同一个百度详情页，有时会出现这种情况，cangoback方法没有触发，接入我的项目之后才出现的，在你的demo中我没复现

**Comment by xiubojin** [comment]
我还是复现不出来，你最近还有这个问题吗？

**Comment by G-Triumphant** [comment]
针对你这个无法返回的问题，可以改为 
NSMutableURLRequest *req = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:webUrl]]; req.HTTPMethod = "POST";
然后再使用loadRequest去请求这个req

**Comment by G-Triumphant** [comment]
针对你这个无法返回的问题，可以改为 
NSMutableURLRequest *req = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:webUrl]]; req.HTTPMethod = "POST";
然后再使用loadRequest去请求这个req
