### ISSUE TITLE
你好，你的demo如何拦截URL,为啥回调没有响应

### ISSUE THREAD

**Issue by Travis990** [xiubojin/JXBWebKit#42]
![image](https://user-images.githubusercontent.com/6883210/61920739-30790d80-af8d-11e9-8447-48bbbc43a2d3.png)
- (void)interceptURL:(NSURL *)URL 没有响应
然后
![image](https://user-images.githubusercontent.com/6883210/61920803-65856000-af8d-11e9-80b6-2c915f9f981c.png)
也没有调用，如何才可以调用拦截的ULR

**Comment by xiubojin** [comment]
这个方法在最新的版本中已经没有了，你想用它做什么？

**Comment by Travis990** [comment]
我下载就是你的GitHub上最新的版本,就是做网站里面的url链接的获取

**Comment by Travis990** [comment]
帅哥 ，有没有遇到过这种问题,
![image](https://user-images.githubusercontent.com/6883210/61921126-9a45e700-af8e-11e9-833a-7ddd7a82cf74.png)
人机身份验证，API参数无效

**Comment by xiubojin** [comment]
你截图截错了。

设置属性值：self.needInterceptRequest = YES;
拦截URL：
`- (void)interceptRequestWithNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
    NSLog(@"当前加载的url:%@", navigationAction.request.URL);
    decisionHandler(WKNavigationActionPolicyAllow);
}`

**Comment by Travis990** [comment]
我添加了这个属性值,浏览器加载不了，这是为啥？

**Comment by xiubojin** [comment]
你遇到这个问题和设置这个属性无关啊。

**Comment by xiubojin** [comment]
> 你遇到这个问题和设置这个属性无关啊。

**Comment by xiubojin** [comment]
这个页面是你首次请求的页面吗？页面的URL是多少？我试试，或者你+我vx:408205555
