### ISSUE TITLE
didFinishNavigation不回调

### ISSUE THREAD

**Issue by kaioser** [xiubojin/JXBWebKit#43]
同样的url，自己在一个vc里初始化一个wkwebview，加载结束后会回调didFinishNavigation代理方法，但是作者这个库里未执行didFinishNavigation方法，求教

**Comment by xiubojin** [comment]
url给我

**Comment by kaioser** [comment]
我就用的百度的首页，http://www.baidu.com/

**Comment by xiubojin** [comment]
![WX20190801-095149](https://user-images.githubusercontent.com/23068582/62259751-14201980-b442-11e9-9838-f3ba7330b3e1.png)

走了。
