### ISSUE TITLE
容器内webview的预加载性能没有明显改善

### ISSUE THREAD

**Issue by dustturtle** [xiubojin/JXBWebKit#44]
实际测试了几十次（ios12,iphone8,4g网络,release版本），发现_prepare是否开启对网页的加载速度几乎没有影响（预计在几十ms以内，因为网络波动，无法更精确的看出）。
我使用的是CFAbsoluteTimeGetCurrent的高精度时间戳，记录了发起页面打开的点击到页面didFinishLoad的时间。

请教下作者有没有做过相关的profiling啊？还是说在老版本的系统和设备上可以获得较大的提升？

**Comment by dustturtle** [comment]
@xiubojin

**Comment by xiubojin** [comment]
_prepare是优化WebView内核启动速度，而不是网页的加载速度。

优化网页加载速度可以使用预加载或者直接把静态资源下载到本地，前端也需要做一些优化。

**Comment by dustturtle** [comment]
怎么才能度量这个优化的结果呢，你说的这个速度？ 我记录了发起页面打开的点击到页面didFinishLoad的时间，因为这个是可度量的。 
你还是没有正面回答我的问题啊：有没有相关的profiling表示这个性能提升
