### ISSUE TITLE
Completion handler passed to -[_WKWebViewDelegateDispatcher webView:decidePolicyForNavigationAction:decisionHandler:] was not called

### ISSUE THREAD

**Issue by hatjs880328s** [xiubojin/JXBWebKit#45]
你好，
我们在使用你这个库的时候，发现bugly上面有很多关于这个得报错。

正常使用没有问题。但是打开APP，然后推到后台，再打开其他app让可用内存变低后，就会收集到这个BUG

可用内存大小 | 25.32 MB ( 2.56% ) |
可用存储空间 | 14.53 GB ( 24.38% )
Bugly SDK版本号 | 2.5.0
使用时长： 1 小时 45 分 36 秒

这个时长算少的，基本都是隔夜这种情况。

**Comment by hatjs880328s** [comment]
这个bug，按理说只要任何情况都执行了  回调函数就不会出现，
也正如表现出来的： 正常情况确实没有问题。

但应该是代码再什么情况下并没有处理到调用回调的地方。

**Comment by xiubojin** [comment]
+我vx:408205555

**Comment by xiubojin** [comment]
1.1.2版本修复
