### ISSUE TITLE
第一次请求 带上了cookie，游览器没有获取到cookie 如何解决

### ISSUE THREAD

**Issue by SmallWeed** [xiubojin/JXBWebKit#47]

**Comment by SmallWeed** [comment]
![image](https://user-images.githubusercontent.com/11731944/64579142-5c711680-d3b4-11e9-8a1d-5467c3554730.png)

**Comment by xiubojin** [comment]
描述下请求的详细信息，是否存在302跳转？

**Comment by xiubojin** [comment]
如果还有问题请将此Issue打开。
