### ISSUE TITLE
cookie的设置

### ISSUE THREAD

**Issue by Jing2684** [xiubojin/JXBWebKit#48]
请问下，我通过你的demo测试发现我把原生cookie设置的相关代码去掉，在wkwebview的一个页面,网页设置了cookie，退出后，重新进入浏览器还是可以有cookie的，但是如果你的网页不是通过getReusedWebViewForHolder初始化的就没有这个cookie了，不是很理解,这个cookie同步真实起作用的哪个

**Comment by xiubojin** [comment]
怎么设置的cookie，document.cookie吗？

**Comment by Jing2684** [comment]
是的，document.cookie = cookieKey + i + "=" + Math.random();

**Comment by xiubojin** [comment]
> 是的，document.cookie = cookieKey + i + "=" + Math.random();

document.cookie设置的cookie不会同步到cookie存储域，所以新创建的WebView是没有的，根据你的情况，通过getReusedWebViewForHolder拿到的WebView始终都是那一个WebView，因为第一次用的时候已经设置过cookie了，所以下次复用的时候还有。

**Comment by Jing2684** [comment]
我知道了，谢谢，共用一个wkprocesspool好像就可以了
