### ISSUE TITLE
无法响应Html中的点击事件

### ISSUE THREAD

**Issue by boyXiong** [xiubojin/JXBWebKit#56]
<span style="text-decoration:underline;cursor:hand;color:blue" onclick="toDownload('143953','我爱我家.pdf',false);">我爱我家.pdf(1094K)</span>

无法响应这样的 Html 中的代码 , 这个是查看文件

**Comment by boyXiong** [comment]
0.0 这个 html 代码片段会被屏蔽掉？？？
`
， <span style="text-decoration:underline;cursor:hand;color:blue" onclick="toDownload('143953','我爱我家.pdf',false);"> 我爱我家.pdf(1094K)</span>

`
是这个片段

**Comment by boyXiong** [comment]
`， <span style="text-decoration:underline;cursor:hand;color:blue" onclick="toDownload('143953','我爱我家.pdf',false);"> 我爱我家.pdf(1094K)</span>`

**Comment by xiubojin** [comment]
toDownload应该是个函数吧？

**Comment by boyXiong** [comment]
是的， js 函数

**Comment by xiubojin** [comment]
方便贴下代码吗？

**Comment by boyXiong** [comment]
可以的
`<span style="text-decoration:underline;cursor:hand;color:blue" onclick="toDownload('a82','我爱我家.pdf',false);">附件1：我爱我家.pdf(1827K)</span>`

这个无法响应

**Comment by xiubojin** [comment]
哥，我说的是toDownload这个函数里的代码

**Comment by xiubojin** [comment]
有问题再打开吧

**Comment by boyXiong** [comment]
有问题啊，老哥，代码是这样的

`function toDownload(fid,fname,isopenwin) {
	fname = encodeURI(fname);// 含有%等特殊字符字段手机端下载不了问题，url前端无法解析，encode 下。
	if(isopenwin){
		//if(fid) location = "/download.do?fileid="+fid+"&filename="+fname+"&fromWF=true&requestid=" + js_requestid +"&module=" + js_module 
		if(fid){
	        var locationHref = "/download.do?fileid="+fid+"&filename="+fname+"&fromWF=true&requestid=" + js_requestid +"&module=" + js_module 
	        
	        try{
	            locationHref += "&f_weaver_belongto="+f_weaver_belongto+"&f_weaver_belongto_usertype"
	        }catch(e){
	        }
	        location = locationHref;
		}
	} else {
		var locationHref = "/download.do?download=1&fileid="+fid+"&filename="+fname
        try{
            locationHref += "&f_weaver_belongto_userid="+f_weaver_belongto_userid+"&f_weaver_belongto_usertype="
        }catch(e){
        }
        window.open(locationHref,'_blank');
	}
}`
