### ISSUE TITLE
请教个WK的goback的问题？

### ISSUE THREAD

**Issue by Lee0820** [xiubojin/JXBWebKit#57]
今天意外发现，当wk中点击某个按钮跳转到二级界面的时候，此时APP退到后台，然后再返回前台，此时goback，回到之前的一级页面应该是刷新了页面，之前跟h5 沟通定义的方法是只有进入的时候调用的一些js交互，此时发生了回调，如果没有退到后台的操作，没有发生调用，不清楚是不是系统做了什么操作，请教下！

**Comment by xiubojin** [comment]
你把js交互先注释了还会发生这种问题吗？

**Comment by Lee0820** [comment]
什么意思，先注释js交互是指什么

**Comment by xiubojin** [comment]
这个不是goback的问题，有位开发者提交的request代码有问题，我刚刚已经修复了。你在pod里依赖1.1.3版本。没问题了话把这个issue关掉。

**Comment by Lee0820** [comment]
额，我的问题跟这个JXBWKWebView   没关系，感觉像是 WKWebView的机制问题，我先关了吧
