### ISSUE TITLE
updateNavigationItems为什么要每次都刷新setLeftBarButtonItems？

### ISSUE THREAD

**Issue by BeWithU** [xiubojin/JXBWebKit#58]
https://github.com/xiubojin/JXBWKWebView/blob/20094fdcafd6ebcbd37da8ea9f0552b036dd284e/JXBWebKit/JXBWebViewController.m#L195

1，updateNavigationItems只刷新手势就可以了吧，为什么要每次都更新一下leftBarButtonItem，这样会导致网页加载完成之后，通过backImagePath设置都返回都图片无法正常显示，会显示系统默认都返回按钮
2，showCloseNavLeftItem属性是否应该公开出来，由调用方决定是否显示？现在看起来只能是YES，不能更改。

**Comment by xiubojin** [comment]
1、点击返回、关闭按钮或者手势返回，WebView每次请求load完成都需要刷新导航栏按钮。你说的无法正常显示，你是自己又设置了图片吗？
2、这个属性可以通过KVC修改的。

**Comment by xiubojin** [comment]
有问题再打开吧
