### ISSUE TITLE
Ajax的post请求的body为空

### ISSUE THREAD

**Issue by ipad4** [xiubojin/JXBWebKit#6]
Ajax的post请求的body为空，这个貌似无法解决

**Comment by xiubojin** [comment]
是不是利用NSURLProtocol拦截WebView所有请求了？
如果是的话就会造成这种问题。

另外，不知道你想解决什么问题？

**Comment by ipad4** [comment]
是开启NSURLProtocol了，这个库也是没有解决这个问题吗。我想解决wkwebview加载网页时根据网络请求判断本地离线资源包中是否存在相应资源（比如jquery等公共资源），然后从本地读取资源文件，回传给wkwebview展示

**Comment by xiubojin** [comment]
开启NSURLProtocol拦截请求，post请求的body必然会丢失的，我这个库只在首次是post请求的时候解决了这个问题，实现代码都在loadPostRequest方法里，你可以参照这个对其他post请求进行修改。

**Comment by ipad4** [comment]
首次是post请求，这个应用场景能具体讲讲吗，一般打开网页貌似用不上呀

**Comment by xiubojin** [comment]
[WKWebView指南](https://www.jianshu.com/p/97faf098e673)
看post请求那一节

**Comment by xiubojin** [comment]
[WKWebView指南](https://www.jianshu.com/p/97faf098e673)
看post请求那一节

**Comment by hatjs880328s** [comment]
H5页面中的ajax请求，我们根本就拦截不到吧。使用urlprotocol的时候body已经是null了。
你文章中说将body当做header存起来，并且将http更改为post是在这里处理吗？ 
谢谢回答。
