### ISSUE TITLE
不添加个子控制器重新加载的入口吗？都是初始化和request绑定了。

### ISSUE THREAD

**Issue by zmh10241015** [xiubojin/JXBWebKit#61]

**Comment by xiubojin** [comment]
？

**Comment by zmh10241015** [comment]
由于需求不一样，初始化时候，我不直接传入一个url字符串、或者一个URL，或者一个request。后来我发现有一个封装的webView，我是直接使用控制器的webView属性去加载一个URL。还没认真看源码，这样加载有没什么隐患。就想问一下，没有可能暴露一个api让自己可以自由控制加载时间点。之前描述有点乱

**Comment by xiubojin** [comment]
可以派生出一个子控制器，重写加载URL的那个方法，你就可以自己控制了。
