### ISSUE TITLE
发现ios9系统H5调用js没反应

### ISSUE THREAD

**Issue by shenyue999** [xiubojin/JXBWebKit#63]
发现ios9系统H5调用js没反应

**Comment by xiubojin** [comment]
发代码

**Comment by shenyue999** [comment]
function getAccessTokenInit() {
    window.JXBJSBridge.call({
        target : "Ben",
        action : "list",
        data : {'callback' : 'accessTokenCode'},
        callback : {

        }
    });
}

var accessTokenCode = function (data) {
    access_token = data.token;
    inviteCode = data.inviteCode;

    if (access_token) {
        getInviteLogData();
    }
}

**Comment by shenyue999** [comment]
var access_token = '',
    inviteCode = '',
    isAndroid;

$(function () {
    $('.share-area').css('display', 'none')
    var swiper = new Swiper('.swiper-container', {
        slidesPerView: "auto",
        spaceBetween: 20,
        loop: true,
        centeredSlides: true
    })
    // $('.close-btn').click(function () {
    //     $('.share-area').css('display', 'none')
    // })
    // $('.share-link').click(function () {
    //     console.log('1')
    //     $('.share-area').css('display', 'block')
    // })
    // $('.share-posters').click(function () {
    //     $('.share-area').css('display', 'block')
    // })

    var u = navigator.userAgent;
    isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
    if (!isAndroid) {
        getAccessTokenInit();
    } else {
        // 安卓直接跳用返回
        access_token = JXBJSBridge.getToken();
        inviteCode = JXBJSBridge.getUnique();

        if (access_token) {
            getInviteLogData();
        }
    }


    // getAccessTokenInit();
})

function getAccessTokenInit() {
    window.JXBJSBridge.call({
        target : "Ben",
        action : "list",
        data : {'callback' : 'accessTokenCode'},
        callback : {

        }
    });
}

var accessTokenCode = function (data) {
    access_token = data.token;
    inviteCode = data.inviteCode;

    if (access_token) {
        getInviteLogData();
    }
}

function shareInvite(type)
{
    if (!isAndroid) {
        window.JXBJSBridge.call({
            target : "Ben",
            action : "share",
            data : {'type' : type},
            callback : {

            }
        });
    } else {
        if (type == 'url') {
            type = 'link';
        }

        JXBJSBridge.share(type);
    }
}

function getInviteLogData()
{
   
}

function copyText()
{
    if (isAndroid) {
        JXBJSBridge.copyUnique(inviteCode);
    } else {
        window.JXBJSBridge.call({
            target : "Ben",
            action : "copyInviteCode",
            data : {},
            callback : {

            }
        });
    }
}

**Comment by xiubojin** [comment]
发调用的代码就行了！
