### ISSUE TITLE
你好 点击崩溃

### ISSUE THREAD

**Issue by MoShenGuo** [xiubojin/JXBWebKit#65]
![image](https://user-images.githubusercontent.com/21171688/77739101-ee3c2a80-704b-11ea-956d-d1b7b844245e.png)
这个为什么点击崩溃呢?求指教

**Comment by MoShenGuo** [comment]
你好 我这边可以拿你webView封装的 但是不需要你跟js耦合性太强了,用你的话 还得前端也要修改,我这边有WebViewJavascriptBridge注册的  有什么办法解决吗?谢谢

**Comment by xiubojin** [comment]
你的bridge是基于什么做的

**Comment by MoShenGuo** [comment]
基于第三方WebViewJavascriptBridge写的,像这个
![image](https://user-images.githubusercontent.com/21171688/77866246-dee3f980-7264-11ea-8474-d4ab046d4c20.png)注册,还有
![image](https://user-images.githubusercontent.com/21171688/77866273-f7ecaa80-7264-11ea-8cfa-d7ca83150a7b.png)像这样的,你这边怎处理呢?谢谢

**Comment by MoShenGuo** [comment]
> 你的bridge是基于什么做的

你好 还有一个问题  有关设置cookies你这边是怎么处理的呢?你一开始就设置cookies吗?中途H5请求体需要再添加cookies吗?谢谢

**Comment by xiubojin** [comment]
崩溃的你打断点调试一下吧。

种cookie需要区分场景，看你们的需求。

**Comment by MoShenGuo** [comment]
> 崩溃的你打断点调试一下吧。
> 
> 种cookie需要区分场景，看你们的需求。

你好 我这边可以拿你webView封装的 但是不需要你跟js耦合性太强了,用WebViewJavascriptBridge分离出来js事件出来怎么分离呢?谢谢

**Comment by xiubojin** [comment]
你要是想换bridge直接把我注册messagehandler的代码删了就行了，然后换成你自己的。
