### ISSUE TITLE
cookie 设置无效

### ISSUE THREAD

**Issue by zhangxianglin** [xiubojin/JXBWebKit#68]
![image](https://user-images.githubusercontent.com/11385670/82321507-82e95600-9a07-11ea-9b34-86ab1288d8f3.png)

设置了cookie，但是用safari看了一下，没有cookie.
很急。。谢谢

**Comment by xiubojin** [comment]
使用cookie的方式有很多，有给服务器用的，有给ajax用的，你的是哪种？

**Comment by zhangxianglin** [comment]
> 使用cookie的方式有很多，有给服务器用的，有给ajax用的，你的是哪种？

就是正常app登录后，把token之类的东西放到cookie里面，给h5使用。

**Comment by xiubojin** [comment]
那你这种情况得使用document.cookie设置cookie才能给h5用。
