### ISSUE TITLE
NavigationBar显示不出来

### ISSUE THREAD

**Issue by jakyou** [xiubojin/JXBWebKit#70]
你好,很高兴用到这么好用的代码,目前我使用这个lib开发,没有使用storyborad的情况下,NavigationBar显示不是来,查看了源码与文档,以及demo,并没有发现纯代码需要怎么写才能显示出来,麻烦了

**Comment by xiubojin** [comment]
这个库并没有操作NavigationBar，建议检查下相关的代码
