### ISSUE TITLE
继承JXBWebViewController的子控制器放在UITabBarController的时候,如果直接切换UIWindow的根控制器会崩溃

### ISSUE THREAD

**Issue by GSmoke** [xiubojin/JXBWebKit#72]
- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    if (_showProgressView) {
        **[_webView removeObserver:self forKeyPath:@"estimatedProgress"];**
    }
    [_webView removeObserver:self forKeyPath:@"title"];
    if (!_terminate) {
        [[JXBWKWebViewPool sharedInstance] recycleReusedWebView:_webView];
    }
}

**Comment by xiubojin** [comment]
1.2.1已解决
