### ISSUE TITLE
上架到App Store会收到一封警告邮件？

### ISSUE THREAD

**Issue by flyzhu27** [xiubojin/JXBWebKit#73]
好像是说截止2020年12月，不能提交带有UIWebView api的app了。部分邮件内容如下：
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by xiubojin** [comment]
pod 'JXBWebKit', '~> 1.2.0'
最新版已经移除了UIWebView相关代码
