### ISSUE TITLE
移除监听崩溃

### ISSUE THREAD

**Issue by xingyuemitu** [xiubojin/JXBWebKit#77]
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <JXBWebViewController 0x11bd4deb0> for the key path "title" from <JXBWKWebView 0x11c06ba00> because it is not registered as an observer.'

在使用JXBWebViewController的时候创建后，先调用了dealloc方法

**Comment by xiubojin** [comment]
1.2.1已解决
