### ISSUE TITLE
获取不到导航栏返回图

### ISSUE THREAD

**Issue by ZhangDengfengGit** [xiubojin/JXBWebKit#79]
- (UIBarButtonItem *)backItem {
    if (_backItem) return _backItem;
    //NSString *backImgPath = [_resourcePath stringByAppendingString:@"/webView_back"];
    NSString *bundlePath = _backImagePath ?: [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"JSResources.bundle"];
    NSString *backImgPath = [bundlePath stringByAppendingPathComponent:@"webView_back"];
    UIImage *backImage = [UIImage imageNamed:backImgPath];
    _backItem = [[UIBarButtonItem alloc] initWithImage:backImage
                                                 style:UIBarButtonItemStylePlain
                                                target:self
                                                action:@selector(backItemClick:)];
    return _backItem;
}
pod集成到项目中，在这个方法中无论如何都获取不到返回图片，点击返回箭头位置左边屏幕边缘有返回操作，但显示不出来返回箭头，请大神帮忙查看

**Comment by ZhangDengfengGit** [comment]
我确认了问题：在pod中使用use_frameworks!的话，获取图片资源的方法有问题，不能获取到

**Comment by xiubojin** [comment]
1.2.1已解决
