### ISSUE TITLE
readme 更新下 go环境配置

### ISSUE THREAD

**Issue by iStig** [xiubojin/JXBWebKit#8]
使用`vim`打开`.bash_profile`进行编辑，`i`进行编辑，编辑完成后`:wq`退出，编辑内容如下：

````
export GOPATH=/Users/<your name>/Documents/go    //更改为Documents
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
````
//增加一个步骤    使用`cd ~`切换到根目录 输入 source .bash_profile
（4）切换到`Documents`文件夹，创建`go`文件夹，再在`go`文件夹下分别创建`bin`、`src`文件夹，`src`就是以后存放项目的文件夹.

（5）在终端输入`go env`命令查看配置是否正确，`GOBIN`有值表示配置没问题.

（6）在本工程内搜索文件夹`GoProject > src > OfflineServer`，将`OfflineServer`文件夹拷贝至`Douments > go > src`目录下. //更改为Documents

（7）切换至`Documents > go > src` //更改为Documents

**Comment by iStig** [comment]
现在我通过6）把offlineServer拷贝到了 Douments > go > src目录下 现在的目录接口是Douments > go > src > offlineServer   这时候通过7）切换到 Documents > go > src 运行 run build 报错 can't load package: package .: no Go files in /Users/istig/Documents/go/src

**Comment by iStig** [comment]
我尝试在Douments > go > src > offlineServer 输入命令 go build 生成一个unix可执行文件 名字为OfflineServer
接着继续在Douments > go > src > offlineServer 目录下运行 go run 报错go run: no go files listed

**Comment by iStig** [comment]
请问这个readme 对于go的配置是否有点问题

**Comment by xiubojin** [comment]
export GOPATH=/Users/<your name>/Documents/go    //更改为Documents
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

第一行your name那里应该放你mac的名字。

**Comment by iStig** [comment]
> export GOPATH=/Users//Documents/go //更改为Documents
> export GOBIN=$GOPATH/bin
> export PATH=$PATH:$GOBIN
> 
> 第一行your name那里应该放你mac的名字。

这个没问题 
export GOPATH=/Users/istig/Documents/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
我是这么配置的 

只是后面走 go build 和 go run 报错

**Comment by xiubojin** [comment]
切换到Douments > go > src > offlineServer，执行go run main.go

main.go是入口

**Comment by xiubojin** [comment]
额，你要是能用就先这么用着吧。但其实你这种解决方法严格来说是不正确的，GOPATH包含的每个路径都是一个工作区，Go语言的源码文件都需要被存放在环境变量GOPATH包含的某个工作区中的src目录下的某个代码包（目录）中。

**Comment by iStig** [comment]
> 额，你要是能用就先这么用着吧。但其实你这种解决方法严格来说是不正确的，GOPATH包含的每个路径都是一个工作区，Go语言的源码文件都需要被存放在环境变量GOPATH包含的某个工作区中的src目录下的某个代码包（目录）中。
嗯 你说的没错 我去掉了上面的一层回复
