### ISSUE TITLE
只支持JXBJSBridge调用吗？是否支持window.WebKit.call

### ISSUE THREAD

**Issue by kaioser** [xiubojin/JXBWebKit#91]

**Comment by xiubojin** [comment]
JXBJSBridge封装了window.WebKit.call

**Comment by kaioser** [comment]
> JXBJSBridge封装了window.WebKit.call

好的谢谢

**Comment by kaioser** [comment]
> JXBJSBridge封装了window.WebKit.call

您好，如果前端的代码是这样调用的话，OC这边建文件应该用什么命名呢？Service_messageHandlers吗？
<img width="623" alt="截屏2020-12-17 下午5 10 59" src="https://user-images.githubusercontent.com/30762999/102467416-3b08db00-408b-11eb-902b-d0b0e43f99e0.png">
