### ISSUE TITLE
有一个SEGV_ACCERR的问题麻烦帮看下

### ISSUE THREAD

**Issue by wuyj** [xiubojin/JXBWebKit#94]
JavaScriptCore | bmalloc::Environment::Environment(std::__1::lock_guard<bmalloc::Mutex> const&) + 20
-- | --
3 JavaScriptCore | bmalloc::StaticPerProcess<bmalloc::Environment>::getSlowCase() + 92
4 JavaScriptCore | bmalloc::Cache::allocateSlowCaseNullCache(bmalloc::HeapKind, unsigned long) + 120
5 JavaScriptCore | JSC::ExecutableAllocator::initialize() + 16
6 JavaScriptCore | _ZNSt3__117__call_once_proxyINS_5tupleIJOZN3JSC19initializeThreadingEvE3$_0EEEEEvPv + 48
7 libc++.1.dylib | std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) + 160
8 JavaScriptCore | JSC::initializeThreading() + 72
9 WebKit | WebKit::runInitializationCode(void*) + 24
10 libc++.1.dylib | std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) + 160
11 WebKit | WebKit::InitializeWebKit2() + 72
12 WebKit | -[WKWebViewConfiguration init] + 60
13 闪聚 | +[JXBWKWebView defaultConfiguration] (JXBWKWebView.m:183)
14 闪聚 | +[JXBWKWebView webView] (JXBWKWebView.m:0)
15 闪聚 | __40-[JXBWKWebViewPool _prepareReuseWebView]_block_invoke (JXBWKWebViewPool.m:0)
16 libdispatch.dylib | __dispatch_call_block_and_release + 24
17 libdispatch.dylib | __dispatch_client_callout + 16
18 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$mp + 904
19 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
20 CoreFoundation | ___CFRunLoopRun + 1724
21 CoreFoundation | CFRunLoopRunSpecific + 424
22 GraphicsServices | GSEventRunModal + 160
23 UIKitCore | UIApplicationMain + 1932
24 闪聚 | main (main.m:14)
25 libdyld.dylib | _start + 4

**Comment by xiubojin** [comment]
这个webkit内核崩溃没法解决，你看看这个崩溃发生的版本旧不旧，数量多不多，如果版本旧、数量非常少的话就不用管。实在不行你可以把JXBWKWebViewPool的load方法注释掉，但是治标不治本，可能以后其他地方初始化WKWebViewConfiguration的时候还会发生这样的崩溃。
